name: commit-message
on: push
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Extract commit message
        id: commit-message
        if: always()
        env:
          COMMIT: ${{ github.event.head_commit.message }} 
        run: |
           npm install @actions/core
           node - <<EOF
             const core = require('@actions/core');
             const message = process.env.COMMIT;
             console.log("JSON MEssage is ",${{ toJSON(github.event.head_commit.message) }})
             const result = message.split('Signed-off-by:')[0].trim();
             core.setOutput('COMMIT_MESSAGE', result); 
             const result_message = result.replace(/\n/g, ' ');
             console.log("Message is", result);
             console.log("Message is", result_message);
           EOF
