name: run-tests

on:
  pull_request:
    types: [opened, reopened]
        
env:
  BUILD_TOOL_VERSION: 32.0.0
  
jobs:
  status_job:
    runs-on: ubuntu-latest
    steps:
    - name: Set commit status (success)
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${{github.repository}}
        echo ${{ github.event.pull_request.head.sha }}        
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/statuses/${{ github.event.pull_request.head.sha }}\
        -d '{"state":"success","description":"The build succeeded!","context":"custom-status-check"}'
    # - name: Read Status
    #   run: |
    #     echo "Read"
    #     STATE="success"
    #     DESCRIPTION="The build succeeded!"
    #     curl -L \
    #      -X POST \
    #      -H "Accept: application/vnd.github+json" \
    #      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
    #      -H "X-GitHub-Api-Version: 2022-11-28" \
    #      https://api.github.com/repos/${{github.repository}}/statuses/${{ github.event.pull_request.head.sha }} \
    #      -d '{"state":"success","description":"The build succeeded!","context":"custom-status-check"}'



         
         # -d "{\"state\":\"${STATE}\",\"description\":\"${DESCRIPTION}\",\"context\":\"custom-status-check\"}"



          
