name: run-tests

on:
  pull_request:
    types: [opened, reopened]
        
env:
  BUILD_TOOL_VERSION: 32.0.0
  
jobs:
  status_job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Test
      id: try
      run: echo "Test"
    - name: Set commit status (success)
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${{github.sha}}
        echo ${{ github.event.pull_request.head.sha }}  
        echo ${{ steps.try.outcome}}
        if [ 'trial' == 'trial' ] && [ "${{ steps.try.outcome }}" == 'success' ]; then
          STATE="success"
          DESCRIPTION="The build succeeded!"
        else
          STATE="failure"
          DESCRIPTION="The build failed!"
        fi
        curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/${{github.repository}}/statuses/${{ github.event.pull_request.head.sha }} \
         -d "{\"state\":\"${STATE}\",\"description\":\"${DESCRIPTION}\",\"context\":\"custom-status-check\"}"          


          
